#include "themes.h"

// autogenerated, do not modify!
#ifdef __cplusplus
extern "C" {
#endif

#if APP_SUPPORT_FOUND_BLOCK
#include "./serpentx/export/btcscreen1.c"
#else
#include "./serpentx/export/btcscreen.c"
#endif
#include "./serpentx/export/bathwater.c"
#include "./serpentx/export/globalStats.c"
#include "./serpentx/export/netstats.c"
#include "./serpentx/export/clockscreen.c"
#include "./serpentx/export/initscreen2.c"
#include "./serpentx/export/miningscreen2.c"
#include "./serpentx/export/portalscreen.c"
#include "./serpentx/export/settingsscreen2.c"
#include "./serpentx/export/splashscreen2.c"
#include "./serpentx/export/wifi1.c"
#include "./serpentx/export/wifi2.c"
#include "./serpentx/export/wifi3.c"
#include "./serpentx/export/wifi4.c"
#include "./serpentx/export/found.c"
#include "./serpentx/export/eth_0.c"
#include "./serpentx/export/eth_1.c"
#include "./serpentx/export/eth_2.c"

#ifdef __cplusplus
}
#endif
